name: adslay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  firebase_dynamic_links: ^4.1.3
  firebase_messaging: ^11.2.13
  shimmer: ^2.0.0
  fluttertoast: ^8.0.9
  provider: 6.0.1
  shared_preferences: ^2.0.13
  onesignal_flutter: ^3.2.7
  simple_gradient_text: ^1.2.2
  http: ^0.13.4
  progress_dialog_null_safe: ^1.0.7
  get: ^4.6.1
  file_picker: ^4.5.1
  scroll_snap_list: ^0.8.6
  lottie: ^1.3.0
  animated_text_kit: ^4.2.1
  scroll_app_bar: ^2.0.0
  page_transition: ^2.0.5
  carousel_slider: ^4.0.0
  dependencies: ^0.1.5
  carousel_pro: ^1.0.0
  another_flushbar: ^1.10.28
  pinput: ^1.2.0
  flutter_svg: ^1.0.3
  connectivity_plus: ^2.3.0
  responsive_framework: ^0.1.4
  cached_network_image:
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  flutter_credit_card: ^3.0.1
  font_awesome_flutter: ^10.1.0
  stripe_payment: ^1.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #  assets:
  #    - assets

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: Mont-SemiBold
      fonts:
        - asset: assets/fonts/Mont-SemiBold.otf

    - family: Mont-Regular
      fonts:
        - asset: assets/fonts/Mont-Regular.otf

    - family: Mont-Light
      fonts:
        - asset: assets/fonts/Mont-Light.otf

    - family: Mont-Heavy
      fonts:
        - asset: assets/fonts/Mont-Heavy.otf

    - family: Mont-Book
      fonts:
        - asset: assets/fonts/Mont-Book.otf

    - family: Mont-Bold
      fonts:
        - asset: assets/fonts/Mont-Bold.otf



  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
